#!/usr/bin/env python3
"""Lay the ferry's track from Anacortes to Friday Harbor over the real water.

The Washington State Ferries run goes Guemes Channel → Rosario Strait → Thatcher Pass → north of
Lopez → Harney Channel → Wasp Passage → San Juan Channel → Friday Harbor. The waypoints below are
that sequence, read off the chart; between them the track is found over the terrain grid's water
cells (A* with a penalty for hugging the shore) so the drawn line never touches land at the game's
resolution, then thinned. Output: godot/content/ferry_route.json — the track in local metres and
the places to introduce as the ferry comes abeam of them.

    python3 tools/geo/ferry_route.py [godot/terrain] [godot/content/ferry_route.json]
"""
import json, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from water_route import Water, length

WAYPOINTS = [  # id, x east, z south (metres from Friday Harbor), place to introduce here (or None)
    ('anacortes', 24400, 2700, 'anacortes'),
    ('rosario', 19000, 1800, None),
    ('thatcher', 15657, 478, 'thatcherPass'),
    ('lopezSound', 11800, -2600, 'lopez'),
    ('harneyE', 9010, -5304, None),
    ('harney', 7164, -5972, 'orcas'),
    ('harneyW', 5200, -6350, 'shaw'),
    ('wasp', 1400, -6450, 'waspPassage'),
    ('sanJuanChannel', -200, -4000, 'sanJuan'),
    ('turn', 1100, -1900, None),
    ('landing', 300, -650, 'fridayHarbor'),
]

def main():
    tdir = sys.argv[1] if len(sys.argv) > 1 else 'godot/terrain'
    out = sys.argv[2] if len(sys.argv) > 2 else 'godot/content/ferry_route.json'
    water = Water(tdir)
    track, starts = water.track([(w[1], w[2]) for w in WAYPOINTS])
    events = []
    for i, w in enumerate(WAYPOINTS):
        if w[3]:
            events.append({'place': w[3], 'index': starts[i]})
    doc = {
        'from': 'Anacortes', 'to': 'Friday Harbor', 'length_m': round(length(track)),
        'note': 'Generated by tools/geo/ferry_route.py over godot/terrain; local metres, x east, z south, origin Friday Harbor.',
        'track': [[x, z] for x, z in track], 'events': events,
    }
    json.dump(doc, open(out, 'w'), indent=1)
    print('track points', len(track), 'length', round(length(track) / 1000, 1), 'km; events', [(e['place'], e['index']) for e in events])

if __name__ == '__main__':
    main()
