#!/usr/bin/env python3
"""Lay the expedition's legs over the real water.

Each leg is a few waypoints read off the chart; between them the track is found over the terrain
grid's water (see water_route.py), so the drawn route and the leg the boat follows never cross
land at the game's resolution. The teaching text for each leg lives in src/content/expedition.js,
keyed by the same id; this file owns only the geometry. Output: godot/content/legs.json.

    python3 tools/geo/leg_routes.py [godot/terrain] [godot/content/legs.json]
"""
import json, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from water_route import Water, length

LEGS = [
    {
        'id': 'leg1', 'from': 'fridayHarbor', 'to': 'jones',
        # Up the harbour, round Point Caution, north past the Labs and Yellow Island, up the east
        # side of Jones and round into the north cove, which opens to the north.
        'vias': [(420, -700), (900, -1900), (300, -3200), (-500, -5200), (-1500, -7200), (-1300, -8400), (-1500, -9700), (-2200, -9420)],
        'cove': (-2200, -9420), 'coveName': 'Jones Island north cove', 'headingDeg': 32,
        'channel': 'San Juan Channel', 'floodSetDeg': 330,
        # Where the stream runs harder than the channel's figure: the narrows off Point Caution.
        'rips': [{'at': (840, -2320), 'radius': 900, 'factor': 1.35, 'name': 'off Point Caution'}],
        'labels': ['fridayHarbor', 'labs', 'yellow', 'jones', 'shaw', 'spieden', 'orcas'],
    },
    {
        'id': 'leg2', 'from': 'jones', 'to': 'posey',
        # Out of the north cove, west across the top of San Juan Channel, through Spieden Channel
        # under Spieden's grass face, round Davison Head and into the lee of Posey Island.
        'vias': [(-2200, -9420), (-2200, -10050), (-5500, -10450), (-8500, -10400), (-10610, -9830)],
        'cove': (-10610, -9830), 'coveName': 'Posey Island', 'headingDeg': 0,
        'channel': 'Spieden Channel', 'floodSetDeg': 285,  # the flood sets west through the channel toward Haro Strait
        'rips': [{'at': (-8500, -10400), 'radius': 1700, 'factor': 1.8, 'name': 'in the narrows of Spieden Channel'}, {'at': (-10000, -10300), 'radius': 800, 'factor': 1.4, 'name': 'off Davison Head'}],
        'labels': ['jones', 'spieden', 'spiedenChannel', 'davisonHead', 'posey', 'rocheHarbor', 'yellow'],
    },
]

def main():
    tdir = sys.argv[1] if len(sys.argv) > 1 else 'godot/terrain'
    out = sys.argv[2] if len(sys.argv) > 2 else 'godot/content/legs.json'
    water = Water(tdir)
    legs = []
    for leg in LEGS:
        track, _ = water.track(leg['vias'])
        if water.on_land(*leg['cove']):
            raise SystemExit(f"{leg['id']}: cove on land")
        legs.append({
            'id': leg['id'], 'from': leg['from'], 'to': leg['to'], 'coveName': leg['coveName'],
            'headingDeg': leg['headingDeg'], 'length_m': round(length(track)),
            'channel': leg['channel'], 'floodSetDeg': leg['floodSetDeg'],
            'rips': [{'at': list(r['at']), 'radius': r['radius'], 'factor': r['factor'], 'name': r['name']} for r in leg['rips']],
            'waypoints': [[x, z] for x, z in track], 'cove': list(leg['cove']), 'labels': leg['labels'],
        })
        print(leg['id'], 'points', len(track), 'length', round(length(track) / 1000, 1), 'km')
    doc = {'note': 'Generated by tools/geo/leg_routes.py over godot/terrain; local metres, x east, z south, origin Friday Harbor.', 'legs': legs}
    json.dump(doc, open(out, 'w'), indent=1)

if __name__ == '__main__':
    main()
