// Field guide (FR-028). Facts are deliberately conservative and sourced; items marked in
// credits.js as `verify` get a naturalist's check before public release.

export const SPECIES = [
  { id: 'orca', common: 'Orca (killer whale)', scientific: 'Orcinus orca', group: 'Marine mammals', colour: 0x14181c,
    blurb: 'Two kinds of orca share these waters and never mix.',
    facts: ['Southern Residents eat fish — above all Chinook salmon — and travel in three pods, J, K and L. They are listed as endangered.', 'Bigg’s orcas hunt seals, sea lions and porpoises, and are seen here more and more.', 'An adult male’s dorsal fin can stand as tall as a person.'],
    where: 'Haro Strait and San Juan Channel, mostly spring to autumn', approachMetres: 914, sourceIds: ['noaa-species', 'bewhalewise', 'wa-srkw'] },
  { id: 'humpback', common: 'Humpback whale', scientific: 'Megaptera novaeangliae', group: 'Marine mammals', colour: 0x2a3036,
    blurb: 'Once hunted out of the Salish Sea, humpbacks have come back in recent decades.',
    facts: ['They feed on krill and small schooling fish.', 'The pattern under each tail fluke is unique and used to identify individuals.'],
    where: 'Open channels and straits, summer and autumn', approachMetres: 91, sourceIds: ['noaa-species', 'bewhalewise'] },
  { id: 'harbourSeal', common: 'Harbour seal', scientific: 'Phoca vitulina', group: 'Marine mammals', colour: 0x7a746a,
    blurb: 'The most common marine mammal in the Salish Sea.',
    facts: ['They haul out on rocks and beaches to rest, especially at low tide.', 'Pups born in summer are often left alone on shore while the mother feeds — leave them be.'],
    where: 'Rocky reefs and islets everywhere', approachMetres: 91, sourceIds: ['noaa-species', 'noaa-mm'] },
  { id: 'stellerSeaLion', common: 'Steller sea lion', scientific: 'Eumetopias jubatus', group: 'Marine mammals', colour: 0x8a6a45,
    blurb: 'The largest sea lion in the world; big males can weigh around a tonne.',
    facts: ['You will often hear them before you see them — a deep roar across the water.', 'Unlike seals, sea lions have external ear flaps and walk on their flippers.'],
    where: 'Offshore rocks, mostly autumn to spring', approachMetres: 91, sourceIds: ['noaa-species', 'noaa-mm'] },
  { id: 'riverOtter', common: 'River otter', scientific: 'Lontra canadensis', group: 'Marine mammals', colour: 0x4a3a2a,
    blurb: 'The otters you see on these shores are river otters, at home in salt water.',
    facts: ['They den on land and run easily over rocks — sea otters rarely do.', 'Look for them porpoising along the shoreline at dawn and dusk.'],
    where: 'Shorelines and docks', sourceIds: ['wdfw'] },
  { id: 'harbourPorpoise', common: 'Harbour porpoise', scientific: 'Phocoena phocoena', group: 'Marine mammals', colour: 0x40464c,
    blurb: 'Small, shy and quick — often just a glimpse of a dark back and a soft “puff”.',
    facts: ['Among the smallest cetaceans in the world.', 'They returned to Puget Sound after years of absence.'],
    where: 'Open water in the channels', sourceIds: ['noaa-species'] },
  { id: 'baldEagle', common: 'Bald eagle', scientific: 'Haliaeetus leucocephalus', group: 'Birds', colour: 0x3a2a1c,
    blurb: 'The San Juan Islands hold one of the densest nesting populations in the lower 48 states.',
    facts: ['They build huge nests in tall shoreline trees and reuse them for years.', 'Their call is a surprisingly thin, high whistle.'],
    where: 'Tall firs along every shore', sourceIds: ['wdfw'] },
  { id: 'pigeonGuillemot', common: 'Pigeon guillemot', scientific: 'Cepphus columba', group: 'Birds', colour: 0x16161a,
    blurb: 'A black seabird with white wing patches — and startling red feet and mouth.',
    facts: ['They nest in crevices in rocky cliffs and bluffs.', 'They dive and swim underwater using their wings.'],
    where: 'Rocky shores and bluffs', sourceIds: ['eopugetsound'] },
  { id: 'rhinoAuklet', common: 'Rhinoceros auklet', scientific: 'Cerorhinca monocerata', group: 'Birds', colour: 0x3a3a40,
    blurb: 'A relative of the puffins, named for the pale horn on its bill in breeding season.',
    facts: ['They carry fish back to their burrows in the evening.', 'Protection Island in the Strait of Juan de Fuca hosts a large colony.'],
    where: 'Open water in the channels', sourceIds: ['eopugetsound'] },
  { id: 'heron', common: 'Great blue heron', scientific: 'Ardea herodias', group: 'Birds', colour: 0x6a7a8a,
    blurb: 'Stands motionless in the shallows, then strikes.',
    facts: ['Eelgrass beds are rich hunting grounds for small fish.', 'They nest together in colonies high in trees.'],
    where: 'Eelgrass shallows and quiet bays', sourceIds: ['wdfw'] },
  { id: 'oystercatcher', common: 'Black oystercatcher', scientific: 'Haematopus bachmani', group: 'Birds', colour: 0x101010,
    blurb: 'An all-black shorebird with a bright orange-red bill and a loud, piping call.',
    facts: ['It pries limpets and mussels off rocks with its chisel bill.', 'It lives only on rocky shores.'],
    where: 'Rocky shores at the tide line', sourceIds: ['eopugetsound'] },
  { id: 'octopus', common: 'Giant Pacific octopus', scientific: 'Enteroctopus dofleini', group: 'Intertidal & sea life', colour: 0xa0442c,
    blurb: 'The largest octopus species in the world.',
    facts: ['It can change colour and skin texture in a moment.', 'It lives only a few years, dens under rocks, and leaves a midden of crab shells at the door.'],
    where: 'Rocky reefs; rarely, the lowest tide pools', sourceIds: ['wdfw', 'eopugetsound'] },
  { id: 'seaStar', common: 'Ochre sea star', scientific: 'Pisaster ochraceus', group: 'Intertidal & sea life', colour: 0x7a3a8a,
    blurb: 'Purple or orange, clinging to rocks at the low-tide line.',
    facts: ['A classic keystone species: by eating mussels it keeps room on the rocks for many other animals.', 'Sea star wasting disease killed huge numbers from 2013; populations are still recovering.'],
    where: 'Low intertidal rocks', sourceIds: ['eopugetsound'] },
  { id: 'anemone', common: 'Giant green anemone', scientific: 'Anthopleura xanthogrammica', group: 'Intertidal & sea life', colour: 0x3a9a6a,
    blurb: 'Its green colour comes from algae living inside it.',
    facts: ['It catches crabs, mussels and small fish that fall into its tentacles.'],
    where: 'Tide pools and surge channels', sourceIds: ['eopugetsound'] },
  { id: 'nudibranch', common: 'Opalescent nudibranch', scientific: 'Hermissenda', group: 'Intertidal & sea life', colour: 0xf0a040,
    blurb: 'A sea slug in electric orange and blue.',
    facts: ['It eats hydroids and keeps their stinging cells for its own defence.'],
    where: 'Tide pools, docks and eelgrass', sourceIds: ['eopugetsound'] },
  { id: 'moonJelly', common: 'Moon jelly', scientific: 'Aurelia', group: 'Intertidal & sea life', colour: 0xdfe8f0,
    blurb: 'A translucent bell drifting beneath the hull.',
    facts: ['The four horseshoe shapes you can see through the bell are its reproductive organs.'],
    where: 'Calm bays in summer', sourceIds: ['eopugetsound'] },
  { id: 'bioluminescence', common: 'Bioluminescent plankton', scientific: 'Dinoflagellates such as Noctiluca', group: 'Intertidal & sea life', colour: 0x60e0ff,
    blurb: 'On summer nights every paddle stroke can leave a trail of blue sparks.',
    facts: ['Single-celled plankton flash when the water around them is disturbed.'],
    where: 'Dark, calm bays on summer nights', sourceIds: ['eopugetsound'] },
  { id: 'bullKelp', common: 'Bull kelp', scientific: 'Nereocystis luetkeana', group: 'Kelp & seagrass', colour: 0x8a6a2a,
    blurb: 'A brown alga that grows from the seabed to the surface in a single season.',
    facts: ['It can grow many centimetres in a day, buoyed by a gas-filled float.', 'Kelp forests shelter young fish — and they have declined in parts of the Salish Sea.'],
    where: 'Rocky points with good current', sourceIds: ['eopugetsound'] },
  { id: 'eelgrass', common: 'Eelgrass', scientific: 'Zostera marina', group: 'Kelp & seagrass', colour: 0x4a8a3a,
    blurb: 'Not a seaweed but a flowering plant that grows underwater.',
    facts: ['Eelgrass meadows are nurseries for herring and young salmon.'],
    where: 'Sandy and muddy shallows', sourceIds: ['eopugetsound'] },
  { id: 'madrona', common: 'Pacific madrona', scientific: 'Arbutus menziesii', group: 'Trees', colour: 0xb5482d,
    blurb: 'Red bark that peels in curls, leaning out over the water from dry rocky bluffs.',
    facts: ['A broadleaf evergreen: it keeps its glossy leaves all year and sheds its bark instead.'],
    where: 'Sunny bluffs above the shore', sourceIds: ['wdfw'] },
  { id: 'douglasFir', common: 'Douglas fir', scientific: 'Pseudotsuga menziesii', group: 'Trees', colour: 0x2a4a2a,
    blurb: 'The tall conifer of every island skyline.',
    facts: ['Despite its name it is not a true fir.', 'Its cones have three-pointed bracts poking out between the scales.'],
    where: 'Island forests everywhere', sourceIds: ['wdfw'] },
  { id: 'redCedar', common: 'Western red cedar', scientific: 'Thuja plicata', group: 'Trees', colour: 0x5a6a3a,
    blurb: 'Soft, rot-resistant and fragrant — the tree from which Coast Salish canoes are carved.',
    facts: ['It grows best in moist, shaded ground.', 'Its drooping branches and stringy bark make it easy to tell from the firs around it.'],
    where: 'Damp hollows and north-facing slopes', sourceIds: ['wdfw', 'burke'] },
  { id: 'garryOak', common: 'Garry oak', scientific: 'Quercus garryana', group: 'Trees', colour: 0x6a7a3a,
    blurb: 'The only native oak of these islands, standing in open, grassy meadows.',
    facts: ['Garry oak meadows are among the most endangered ecosystems in the region.'],
    where: 'Dry, open meadows', sourceIds: ['wdfw'] },
];

export const speciesById = Object.fromEntries(SPECIES.map((s) => [s.id, s]));
export const SPECIES_GROUPS = [...new Set(SPECIES.map((s) => s.group))];
