## The expedition's legs, as data the plan, the water and the camp all read. The geometry — the
## waypoints over the real water, the cove, the labels — comes from content/legs.json (generated by
## tools/geo/leg_routes.py); the teaching (title, steps, landing, camp) from the exported content
## under the same id. Which leg is current is the save's legIndex; with no App (the headless
## tests) it is the first.
class_name Leg
extends RefCounted

const LAUNCH_HOUR := 9.5
const TOURING_KNOTS := 3.0
## Launch hours the float plan lets you choose from, and the step between them.
const EARLIEST_LAUNCH := 6.0
const LATEST_LAUNCH := 16.0
const LAUNCH_STEP := 0.25
## The tide runs about fifty minutes later each day.
const TIDE_LAG_MINUTES_PER_DAY := 50.0

static var _legs: Array = []

## Every leg, geometry merged with teaching, in order.
static func all() -> Array:
	if not _legs.is_empty():
		return _legs
	var f := FileAccess.open("res://content/legs.json", FileAccess.READ)
	if f == null:
		return []
	var parsed: Variant = JSON.parse_string(f.get_as_text())
	if not (parsed is Dictionary):
		return []
	var teaching: Array = []
	var app := _app()
	if app:
		teaching = app.content.get("legs", [])
	for g in parsed.get("legs", []):
		var leg: Dictionary = g.duplicate()
		for t in teaching:
			if t.id == leg.id:
				leg.merge(t)
		_legs.append(leg)
	return _legs

static func _app() -> Node:
	var ml := Engine.get_main_loop()
	return ml.root.get_node_or_null("App") if ml is SceneTree else null

## Which leg the expedition is on, from the save.
static func index() -> int:
	var app := _app()
	var n := all().size()
	if app == null or n == 0:
		return 0
	return clampi(int(app.save.get("legIndex", 0)), 0, n - 1)

static func current() -> Dictionary:
	var legs := all()
	return legs[index()] if not legs.is_empty() else {}

static func is_last() -> bool:
	return index() >= all().size() - 1

static func waypoints(leg: Dictionary) -> Array[Vector3]:
	var out: Array[Vector3] = []
	for w in leg.get("waypoints", []):
		out.append(Vector3(float(w[0]), 0.0, float(w[1])))
	return out

## Where the leg starts, on the water, and the heading to leave on.
static func start(leg: Dictionary) -> Vector3:
	var w := waypoints(leg)
	return w[0] if not w.is_empty() else Vector3.ZERO

static func heading_deg(leg: Dictionary) -> float:
	return float(leg.get("headingDeg", 0.0))

## The water in the cove where the leg ends and the camp's beach is found from.
static func cove(leg: Dictionary) -> Vector3:
	var c: Array = leg.get("cove", [0, 0])
	return Vector3(float(c[0]), 0.0, float(c[1]))

## The landings a leg can be cut short at when the wind comes up: place ids on the chart.
static func bailouts(leg: Dictionary) -> Array:
	return leg.get("bailouts", [])

static func cove_name(leg: Dictionary) -> String:
	return str(leg.get("coveName", "the cove"))

static func length_m(leg: Dictionary) -> float:
	var s := 0.0
	var w := waypoints(leg)
	for i in range(1, w.size()):
		s += w[i].distance_to(w[i - 1])
	return s

static func hours_at_touring_pace(leg: Dictionary) -> float:
	return length_m(leg) / (TOURING_KNOTS * 1852.0)

## Bearing in degrees true from a to b (x east, z south; 0 = north).
static func bearing_deg(a: Vector3, b: Vector3) -> float:
	return fposmod(rad_to_deg(atan2(b.x - a.x, -(b.z - a.z))), 360.0)

static func clock(hour: float) -> String:
	var mins := int(round(hour * 60.0))  # to the nearest minute: 7 h 50 m held as 7.8333 must not read 07:49
	return "%02d:%02d" % [floori(mins / 60.0) % 24, mins % 60]

## The chosen launch hour from the save when there is an App; the headless tests get the default.
static func launch_hour() -> float:
	var app := _app()
	if app == null:
		return LAUNCH_HOUR
	var suggested := float(current().get("suggestedLaunch", LAUNCH_HOUR))  # the leg's own good hour, until you choose
	return clampf(float(app.save.get("launchHour", suggested)), earliest_launch(), LATEST_LAUNCH)

## The earliest the day can launch: first light, or later when the morning starts with a water run.
static func earliest_launch() -> float:
	var app := _app()
	return EARLIEST_LAUNCH + (float(app.save.get("lateStart", 0.0)) if app else 0.0)

## Every place the expedition launched from, landed at, or named as a bail-out on a day it landed.
static func places_paddled() -> Array:
	var app := _app()
	var out: Array = []
	if app == null:
		return out
	var legs := all()
	for d in app.save.get("days", []):
		var i := int(d.get("leg", -1))
		if i < 0 or i >= legs.size():
			continue
		var leg: Dictionary = legs[i]
		for id in [leg.get("from", ""), leg.get("to", "")] + Array(leg.get("bailouts", [])):
			if str(id) != "" and not out.has(str(id)):
				out.append(str(id))
	return out

## How far a position is off the leg's line: metres to the nearest point of the track.
static func off_track_m(leg: Dictionary, pos: Vector3) -> float:
	var w := waypoints(leg)
	if w.is_empty():
		return 0.0
	var p := Vector2(pos.x, pos.z)
	var best := p.distance_to(Vector2(w[0].x, w[0].z))
	for i in range(1, w.size()):
		var a := Vector2(w[i - 1].x, w[i - 1].z)
		var b := Vector2(w[i].x, w[i].z)
		var q := Geometry2D.get_closest_point_to_segment(p, a, b)
		best = minf(best, p.distance_to(q))
	return best

## How much harder the stream runs here than the channel's figure, and where that is: {factor, name}.
## Rips are authored per leg (tools/geo/leg_routes.py) and fall off smoothly to 1.0 at their radius.
static func flow_at(leg: Dictionary, pos: Vector3) -> Dictionary:
	var best := { "factor": 1.0, "name": "" }
	for r in leg.get("rips", []):
		var at: Array = r.at
		var d := Vector2(pos.x - float(at[0]), pos.z - float(at[1])).length()
		var radius := float(r.radius)
		if d >= radius:
			continue
		var u := 1.0 - d / radius
		var f := 1.0 + (float(r.factor) - 1.0) * (u * u * (3.0 - 2.0 * u))
		if f > float(best.factor):
			best = { "factor": f, "name": str(r.name) }
	return best
